version: '3'
services:
  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: <neon_host> # fx ep-xxx.eu-central-1.aws.neon.tech
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: "true"
    depends_on:
      - guacd

  guacd:
    image: guacamole/guacd
    restart: always
