version: '3'
services:
  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: ep-fancy-grass-a2omc644-pooler.eu-central-1.aws.neon.tech
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: KulVib2025info
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: "true"
    depends_on:
      - guacd

  guacd:
    image: guacamole/guacd
    restart: always
