[[redirects]]
  from = "/api/test"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://kulturskole-infosk-rm.onrender.com/api/:splat"
  status = 200
  force = true
