services:
  - type: web
    name: guacamole-service
    env: docker
    repo: https://github.com/kulvib/kulturskole-infosk-rm
    region: frankfurt
    docker_context: backend/service2_RemoteDesktop
    docker_compose_file: backend/service2_RemoteDesktop/docker-compose.yml
    envVars:
      - key: POSTGRES_HOSTNAME
        value: your-db-host
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DATABASE
        value: guacamole_db
      - key: POSTGRES_USER
        value: guacamole_user
      - key: POSTGRES_PASSWORD
        value: guacamole_pass
