name: MQTT Test

on: [push, workflow_dispatch]

jobs:
  mqtt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install paho-mqtt
      - name: Run MQTT test
        run: python backend/services/test_mqtt.py
